# Changes here will be overwritten by Copier
_commit: v2.0.0
_src_path: gh:lincc-frameworks/python-project-template
author_email: klaus.zimmermann@quansight.com
author_name: Klaus Zimmermann
create_example_module: true
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: true
include_docs: true
include_notebooks: false
mypy_type_checking: none
package_name: cfgraphman
project_license: MIT
project_name: cfgraphman
project_organization: zklaus
python_versions:
- '3.9'
- '3.10'
- '3.11'
